name: CI/CD Pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4   # upgrade from v3 → v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4   # upgrade from v3 → v4
      with:
        dotnet-version: '10.0.203'

    - name: Restore dependencies
      run: dotnet restore TezHealth.sln

    - name: Build
      run: dotnet build TezHealth.sln --no-restore --configuration Release

    - name: Run tests
      run: dotnet test TezHealth.sln --no-build --verbosity normal
